title: Link #博客标题
description: 不要随便贬低自己. #博客描述
keywords: blog,css,html,php #博客关键字
author: "Link"

#title hide and show
hide: (つェ⊂)我藏好啦
show: ´∇｀ 呀被发现啦~

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "txt.atlinker.cn" # change this to the base hostname & protocol for your site
buildtime: "1564416000" #博客建立时的时间戳 可进入https://tool.lu/timestamp/将博客建立时的日期转换成时间戳
           #The timestamp at the time of blog establishment can be entered at https://tool.lu/timestamp/to convert the date at the time of blog establishment into a timestamp.

PJAX: true #启用PJAX，会与评论系统冲突（如不用评论系统建议开启）

paginate: 8 #同时显示的最大文章数，超过自动分页
paginate_path: "page:num"

background_desktop: /theme/1back-desktop-min.png #桌面版背景
background: /theme/1back-min.png #移动版背景
theme_color: F8BBD0

txt-blog:
  date_format: "%b %-d, %Y"

#install emoji
plugins:
  - jemoji
